version: "3"
services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn develop -H 0.0.0.0
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:8000"
